# Generated by Django 4.0.4 on 2022-05-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followed_post_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followed',
            new_name='follow',
        ),
    ]
